---
- name: "Install MacOS Packages"
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - 1password
      - slack
      - spotify
      - todoist
      - visual-studio-code
      - dbngin
      - google-chrome
      - docker
      - dropbox
      - backblaze
      - font-fira-code
      - zoom
      - kitty
    brew_packages:
      - git
      - mysql
      - php
      - node
      - nvm
      - composer
      - neovim
      - tmux
      - ffmpeg
      - mailhog
      - ansible
    upgrade_homebrew_packages: false

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true

    - name: Tap a Homebrew repository, state present
      community.general.homebrew_tap:
        name: homebrew/cask-fonts

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
